export default [{
  cover: 'R6-maps-stadiumbravo.jpg',
  name: 'B号竞技场'
}, {
  cover: 'R6-maps-emeraldplains.jpg',
  name: '翡翠原'
}, {
  cover: 'R6-maps-bank.jpg',
  name: '银行'
}, {
  cover: '540px-R6-maps-border-new.jpg',
  name: '边境'
}, {
  cover: '540px-R6-maps-chalet-new.jpg',
  name: '木屋'
}, {
  cover: '540px-R6-maps-clubhouse.jpg',
  name: '俱乐部'
}, {
  cover: 'R6-maps-coastline.jpg',
  name: '海岸线'
}, {
  cover: 'R6-maps-consulate.jpg',
  name: '领事馆'
}, {
  cover: 'R6-maps-kafe.jpg',
  name: '杜斯妥也夫斯基咖啡馆'
}, {
  cover: 'R6-maps-kanal.jpg',
  name: '运河'
}, {
  cover: '540px-R6-maps-oregon-new.jpg',
  name: '俄勒冈乡间屋宅'
}, {
  cover: 'R6-maps-skyscraper-new.jpg',
  name: '摩天大楼'
}, {
  cover: 'R6-maps-themepark.jpg',
  name: '主题乐园'
}, {
  cover: 'R6-maps-villa.jpg',
  name: '庄园'
}, ]