export default [{
  name: '叉烧',
  avatar: '/avatar/cs.jpg'
}, {
  name: '霸王龙',
  avatar: '/avatar/bwl.jpg'
}, {
  name: '沐月',
  avatar: '/avatar/my.jpg'
}, {
  name: '咸鱼',
  avatar: '/avatar/fish.jpg'
}, {
  name: '干净如风',
  avatar: '/avatar/rufeng.jpg'
}, {
  name: '风叶',
  avatar: '/avatar/fengye.jpg'
}, {
  name: '栖淼',
  avatar: '/avatar/ximiao.jpg'
}, {
  name: '鑫宇',
  avatar: '/avatar/xinyu.jpg'
}, ]